# Generated by Django 5.1.4 on 2025-03-30 13:24

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile_images/default_profile_image.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1280, 1280], upload_to='profile_images/'),
        ),
    ]
